export const Countries = [
  { CodigoArea: '93', Pais: 'Afeganistão', Sigla: 'AF' },
  { CodigoArea: '27', Pais: 'África do Sul', Sigla: 'ZA' },
  { CodigoArea: '355', Pais: 'Albânia', Sigla: 'AL' },
  { CodigoArea: '49', Pais: 'Alemanha', Sigla: 'DE' },
  { CodigoArea: '376', Pais: 'Andorra', Sigla: 'AD' },
  { CodigoArea: '244', Pais: 'Angola', Sigla: 'AO' },
  { CodigoArea: '1264', Pais: 'Anguila', Sigla: 'AI' },
  { CodigoArea: '672', Pais: 'Antártida', Sigla: 'AQ' },
  { CodigoArea: '1268', Pais: 'Antígua e Barbuda', Sigla: 'AG' },
  { CodigoArea: '599', Pais: 'Antilhas Holandesas', Sigla: 'AN' },
  { CodigoArea: '966', Pais: 'Arábia Saudita', Sigla: 'SA' },
  { CodigoArea: '213', Pais: 'Argélia', Sigla: 'DZ' },
  { CodigoArea: '54', Pais: 'Argentina', Sigla: 'AR' },
  { CodigoArea: '374', Pais: 'Armênia', Sigla: 'AM' },
  { CodigoArea: '297', Pais: 'Aruba', Sigla: 'AW' },
  { CodigoArea: '61', Pais: 'Austrália', Sigla: 'AU' },
  { CodigoArea: '43', Pais: 'Áustria', Sigla: 'AT' },
  { CodigoArea: '', Pais: 'Autoridade Palestina', Sigla: 'PS' },
  { CodigoArea: '994', Pais: 'Azerbaijão', Sigla: 'AZ' },
  { CodigoArea: '1242', Pais: 'Bahamas', Sigla: 'BS' },
  { CodigoArea: '973', Pais: 'Bahrein', Sigla: 'BH' },
  { CodigoArea: '880', Pais: 'Bangladesh', Sigla: 'BD' },
  { CodigoArea: '1246', Pais: 'Barbados', Sigla: 'BB' },
  { CodigoArea: '375', Pais: 'Belarus', Sigla: 'BY' },
  { CodigoArea: '32', Pais: 'Bélgica', Sigla: 'BE' },
  { CodigoArea: '501', Pais: 'Belize', Sigla: 'BZ' },
  { CodigoArea: '229', Pais: 'Benin', Sigla: 'BJ' },
  { CodigoArea: '1441', Pais: 'Bermuda', Sigla: 'BM' },
  { CodigoArea: '591', Pais: 'Bolívia', Sigla: 'BO' },
  { CodigoArea: '387', Pais: 'Bósnia e Herzegovina', Sigla: 'BA' },
  { CodigoArea: '267', Pais: 'Botsuana', Sigla: 'BW' },
  { CodigoArea: '55', Pais: 'Brasil', Sigla: 'BR' },
  { CodigoArea: '673', Pais: 'Brunei', Sigla: 'BN' },
  { CodigoArea: '359', Pais: 'Bulgária', Sigla: 'BG' },
  { CodigoArea: '226', Pais: 'Burquina Faso', Sigla: 'BF' },
  { CodigoArea: '257', Pais: 'Burundi', Sigla: 'BI' },
  { CodigoArea: '975', Pais: 'Butão', Sigla: 'BT' },
  { CodigoArea: '238', Pais: 'Cabo Verde', Sigla: 'CV' },
  { CodigoArea: '237', Pais: 'Camarões', Sigla: 'CM' },
  { CodigoArea: '855', Pais: 'Camboja', Sigla: 'KH' },
  { CodigoArea: '1', Pais: 'Canadá', Sigla: 'CA' },
  { CodigoArea: '974', Pais: 'Catar', Sigla: 'QA' },
  { CodigoArea: '7', Pais: 'Cazaquistão', Sigla: 'KZ' },
  { CodigoArea: '235', Pais: 'Chade', Sigla: 'TD' },
  { CodigoArea: '56', Pais: 'Chile', Sigla: 'CL' },
  { CodigoArea: '86', Pais: 'China', Sigla: 'CN' },
  { CodigoArea: '357', Pais: 'Chipre', Sigla: 'CY' },
  { CodigoArea: '39', Pais: 'Cidade do Vaticano', Sigla: 'VA' },
  { CodigoArea: '65', Pais: 'Cingapura', Sigla: 'SG' },
  { CodigoArea: '57', Pais: 'Colômbia', Sigla: 'CO' },
  { CodigoArea: '269', Pais: 'Comoros', Sigla: 'KM' },
  { CodigoArea: '242', Pais: 'Congo', Sigla: 'CG' },
  { CodigoArea: '243', Pais: 'Congo, República Democrática do', Sigla: 'CD' },
  { CodigoArea: '82', Pais: 'Coreia', Sigla: 'KR' },
  { CodigoArea: '850', Pais: 'Coreia do Norte', Sigla: 'KP' },
  { CodigoArea: '506', Pais: 'Costa Rica', Sigla: 'CR' },
  { CodigoArea: '225', Pais: "Côte d'Ivoire (Costa do Marfim)", Sigla: 'CI' },
  { CodigoArea: '385', Pais: 'Croácia', Sigla: 'HR' },
  { CodigoArea: '53', Pais: 'Cuba', Sigla: 'CU' },
  { CodigoArea: '45', Pais: 'Dinamarca', Sigla: 'DK' },
  { CodigoArea: '253', Pais: 'Djibuti', Sigla: 'DJ' },
  { CodigoArea: '1767', Pais: 'Dominica', Sigla: 'DM' },
  { CodigoArea: '20', Pais: 'Egito', Sigla: 'EG' },
  { CodigoArea: '503', Pais: 'El Salvador', Sigla: 'SV' },
  { CodigoArea: '971', Pais: 'Emirados Árabes Unidos', Sigla: 'AE' },
  { CodigoArea: '593', Pais: 'Equador', Sigla: 'EC' },
  { CodigoArea: '291', Pais: 'Eritreia', Sigla: 'ER' },
  { CodigoArea: '421', Pais: 'Eslováquia', Sigla: 'SK' },
  { CodigoArea: '386', Pais: 'Eslovênia', Sigla: 'SI' },
  { CodigoArea: '34', Pais: 'Espanha', Sigla: 'ES' },
  { CodigoArea: '1', Pais: 'Estados Unidos', Sigla: 'US' },
  { CodigoArea: '372', Pais: 'Estônia', Sigla: 'EE' },
  { CodigoArea: '251', Pais: 'Etiópia', Sigla: 'ET' },
  { CodigoArea: '63', Pais: 'Filipinas', Sigla: 'PH' },
  { CodigoArea: '358', Pais: 'Finlândia', Sigla: 'FI' },
  { CodigoArea: '33', Pais: 'França', Sigla: 'FR' },
  { CodigoArea: '241', Pais: 'Gabão', Sigla: 'GA' },
  { CodigoArea: '220', Pais: 'Gâmbia', Sigla: 'GM' },
  { CodigoArea: '233', Pais: 'Gana', Sigla: 'GH' },
  { CodigoArea: '995', Pais: 'Geórgia', Sigla: 'GE' },
  {
    CodigoArea: '',
    Pais: 'Geórgia do Sul e Ilhas Sandwich do Sul',
    Sigla: 'GS',
  },
  { CodigoArea: '350', Pais: 'Gibraltar', Sigla: 'GI' },
  { CodigoArea: '1473', Pais: 'Granada', Sigla: 'GD' },
  { CodigoArea: '30', Pais: 'Grécia', Sigla: 'GR' },
  { CodigoArea: '299', Pais: 'Groenlândia', Sigla: 'GL' },
  { CodigoArea: '', Pais: 'Guadalupe', Sigla: 'GP' },
  { CodigoArea: '1671', Pais: 'Guam', Sigla: 'GU' },
  { CodigoArea: '502', Pais: 'Guatemala', Sigla: 'GT' },
  { CodigoArea: '', Pais: 'Guernsey', Sigla: 'GG' },
  { CodigoArea: '592', Pais: 'Guiana', Sigla: 'GY' },
  { CodigoArea: '', Pais: 'Guiana Francesa', Sigla: 'GF' },
  { CodigoArea: '224', Pais: 'Guiné', Sigla: 'GN' },
  { CodigoArea: '240', Pais: 'Guiné Equatorial', Sigla: 'GQ' },
  { CodigoArea: '245', Pais: 'Guiné-Bissau', Sigla: 'GW' },
  { CodigoArea: '509', Pais: 'Haiti', Sigla: 'HT' },
  { CodigoArea: '504', Pais: 'Honduras', Sigla: 'HN' },
  { CodigoArea: '852', Pais: 'Hong Kong S. A. R', Sigla: 'HK' },
  { CodigoArea: '36', Pais: 'Hungria', Sigla: 'HU' },
  { CodigoArea: '967', Pais: 'Iêmen', Sigla: 'YE' },
  { CodigoArea: '', Pais: 'Ilha Bouvet', Sigla: 'BV' },
  { CodigoArea: '61', Pais: 'Ilha Christmas', Sigla: 'CX' },
  { CodigoArea: '44', Pais: 'Ilha de Man', Sigla: 'IM' },
  { CodigoArea: '672', Pais: 'Ilha Norfolk', Sigla: 'NF' },
  { CodigoArea: '1345', Pais: 'Ilhas Cayman', Sigla: 'KY' },
  { CodigoArea: '61', Pais: 'Ilhas Cocos (Keeling)', Sigla: 'CC' },
  { CodigoArea: '682', Pais: 'Ilhas Cook', Sigla: 'CK' },
  { CodigoArea: '298', Pais: 'Ilhas Faroés', Sigla: 'FO' },
  { CodigoArea: '679', Pais: 'Ilhas Fiji', Sigla: 'FJ' },
  { CodigoArea: '', Pais: 'Ilhas Heard e Ilhas McDonald', Sigla: 'HM' },
  { CodigoArea: '500', Pais: 'Ilhas Malvinas (Falkland Islands)', Sigla: 'FK' },
  { CodigoArea: '1670', Pais: 'Ilhas Marianas do Norte', Sigla: 'MP' },
  { CodigoArea: '692', Pais: 'Ilhas Marshall', Sigla: 'MH' },
  { CodigoArea: '677', Pais: 'Ilhas Salomão', Sigla: 'SB' },
  { CodigoArea: '1649', Pais: 'Ilhas Turks e Caicos', Sigla: 'TC' },
  { CodigoArea: '1340', Pais: 'Ilhas Virgens Americanas', Sigla: 'VI' },
  { CodigoArea: '1284', Pais: 'Ilhas Virgens Britânicas', Sigla: 'VG' },
  { CodigoArea: '91', Pais: 'Índia', Sigla: 'IN' },
  { CodigoArea: '62', Pais: 'Indonésia', Sigla: 'ID' },
  { CodigoArea: '98', Pais: 'Irã', Sigla: 'IR' },
  { CodigoArea: '964', Pais: 'Iraque', Sigla: 'IQ' },
  { CodigoArea: '353', Pais: 'Irlanda', Sigla: 'IE' },
  { CodigoArea: '354', Pais: 'Islândia', Sigla: 'IS' },
  { CodigoArea: '972', Pais: 'Israel', Sigla: 'IL' },
  { CodigoArea: '39', Pais: 'Itália', Sigla: 'IT' },
  { CodigoArea: '1876', Pais: 'Jamaica', Sigla: 'JM' },
  { CodigoArea: '81', Pais: 'Japão', Sigla: 'JP' },
  { CodigoArea: '', Pais: 'Jersey', Sigla: 'JE' },
  { CodigoArea: '962', Pais: 'Jordânia', Sigla: 'JO' },
  { CodigoArea: '686', Pais: 'Kiribati', Sigla: 'KI' },
  { CodigoArea: '965', Pais: 'Kuaite', Sigla: 'KW' },
  { CodigoArea: '856', Pais: 'Laos', Sigla: 'LA' },
  { CodigoArea: '266', Pais: 'Lesoto', Sigla: 'LS' },
  { CodigoArea: '', Pais: 'Letônia', Sigla: 'LV' },
  { CodigoArea: '961', Pais: 'Líbano', Sigla: 'LB' },
  { CodigoArea: '231', Pais: 'Libéria', Sigla: 'LR' },
  { CodigoArea: '218', Pais: 'Líbia', Sigla: 'LY' },
  { CodigoArea: '423', Pais: 'Liechtenstein', Sigla: 'LI' },
  { CodigoArea: '370', Pais: 'Lituânia', Sigla: 'LT' },
  { CodigoArea: '352', Pais: 'Luxemburgo', Sigla: 'LU' },
  {
    CodigoArea: '389',
    Pais: 'Macedônia, Antiga República Iugoslava da',
    Sigla: 'MK',
  },
  { CodigoArea: '261', Pais: 'Madagascar', Sigla: 'MG' },
  { CodigoArea: '60', Pais: 'Malásia', Sigla: 'MY' },
  { CodigoArea: '265', Pais: 'Malaui', Sigla: 'MW' },
  { CodigoArea: '960', Pais: 'Maldivas', Sigla: 'MV' },
  { CodigoArea: '223', Pais: 'Mali', Sigla: 'ML' },
  { CodigoArea: '356', Pais: 'Malta', Sigla: 'MT' },
  { CodigoArea: '212', Pais: 'Marrocos', Sigla: 'MA' },
  { CodigoArea: '', Pais: 'Martinica', Sigla: 'MQ' },
  { CodigoArea: '230', Pais: 'Maurício', Sigla: 'MU' },
  { CodigoArea: '222', Pais: 'Mauritânia', Sigla: 'MR' },
  { CodigoArea: '262', Pais: 'Mayotte', Sigla: 'YT' },
  { CodigoArea: '52', Pais: 'México', Sigla: 'MX' },
  { CodigoArea: '691', Pais: 'Micronésia', Sigla: 'FM' },
  { CodigoArea: '258', Pais: 'Moçambique', Sigla: 'MZ' },
  { CodigoArea: '373', Pais: 'Moldova', Sigla: 'MD' },
  { CodigoArea: '377', Pais: 'Mônaco', Sigla: 'MC' },
  { CodigoArea: '976', Pais: 'Mongólia', Sigla: 'MN' },
  { CodigoArea: '382', Pais: 'Montenegro', Sigla: 'ME' },
  { CodigoArea: '1664', Pais: 'Montserrat', Sigla: 'MS' },
  { CodigoArea: '95', Pais: 'Myanma', Sigla: 'MM' },
  { CodigoArea: '264', Pais: 'Namíbia', Sigla: 'NA' },
  { CodigoArea: '674', Pais: 'Nauru', Sigla: 'NR' },
  { CodigoArea: '977', Pais: 'Nepal', Sigla: 'NP' },
  { CodigoArea: '505', Pais: 'Nicarágua', Sigla: 'NI' },
  { CodigoArea: '227', Pais: 'Níger', Sigla: 'NE' },
  { CodigoArea: '234', Pais: 'Nigéria', Sigla: 'NG' },
  { CodigoArea: '683', Pais: 'Niue', Sigla: 'NU' },
  { CodigoArea: '47', Pais: 'Noruega', Sigla: 'NO' },
  { CodigoArea: '687', Pais: 'Nova Caledônia', Sigla: 'NC' },
  { CodigoArea: '64', Pais: 'Nova Zelândia', Sigla: 'NZ' },
  { CodigoArea: '968', Pais: 'Omã', Sigla: 'OM' },
  { CodigoArea: '31', Pais: 'Países Baixos', Sigla: 'NL' },
  { CodigoArea: '680', Pais: 'Palau', Sigla: 'PW' },
  { CodigoArea: '507', Pais: 'Panamá', Sigla: 'PA' },
  { CodigoArea: '675', Pais: 'Papua-Nova Guiné', Sigla: 'PG' },
  { CodigoArea: '92', Pais: 'Paquistão', Sigla: 'PK' },
  { CodigoArea: '595', Pais: 'Paraguai', Sigla: 'PY' },
  { CodigoArea: '51', Pais: 'Peru', Sigla: 'PE' },
  { CodigoArea: '870', Pais: 'Pitcairn', Sigla: 'PN' },
  { CodigoArea: '689', Pais: 'Polinésia Francesa', Sigla: 'PF' },
  { CodigoArea: '48', Pais: 'Polônia', Sigla: 'PL' },
  { CodigoArea: '1', Pais: 'Porto Rico', Sigla: 'PR' },
  { CodigoArea: '351', Pais: 'Portugal', Sigla: 'PT' },
  { CodigoArea: '254', Pais: 'Quênia', Sigla: 'KE' },
  { CodigoArea: '996', Pais: 'Quirguistão', Sigla: 'KG' },
  { CodigoArea: '853', Pais: 'RAE de Macau', Sigla: 'MO' },
  { CodigoArea: '44', Pais: 'Reino Unido', Sigla: 'UK' },
  { CodigoArea: '236', Pais: 'República Centro-Africana', Sigla: 'CF' },
  { CodigoArea: '1809', Pais: 'República Dominicana', Sigla: 'DO' },
  { CodigoArea: '420', Pais: 'República Tcheca', Sigla: 'CZ' },
  { CodigoArea: '', Pais: 'Reunião', Sigla: 'RE' },
  { CodigoArea: '40', Pais: 'Romênia', Sigla: 'RO' },
  { CodigoArea: '250', Pais: 'Ruanda', Sigla: 'RW' },
  { CodigoArea: '7', Pais: 'Rússia', Sigla: 'RU' },
  { CodigoArea: '508', Pais: 'Saint-Pierre e Miquelon', Sigla: 'PM' },
  { CodigoArea: '685', Pais: 'Samoa', Sigla: 'WS' },
  { CodigoArea: '1684', Pais: 'Samoa Americana', Sigla: 'AS' },
  { CodigoArea: '378', Pais: 'San Marino', Sigla: 'SM' },
  { CodigoArea: '290', Pais: 'Santa Helena', Sigla: 'SH' },
  { CodigoArea: '1758', Pais: 'Santa Lúcia', Sigla: 'LC' },
  { CodigoArea: '239', Pais: 'São Tomé e Príncipe', Sigla: 'ST' },
  { CodigoArea: '1784', Pais: 'São Vicente e Granadinas', Sigla: 'VC' },
  { CodigoArea: '248', Pais: 'Seicheles', Sigla: 'SC' },
  { CodigoArea: '221', Pais: 'Senegal', Sigla: 'SN' },
  { CodigoArea: '232', Pais: 'Serra Leoa', Sigla: 'SL' },
  { CodigoArea: '381', Pais: 'Sérvia', Sigla: 'RS' },
  { CodigoArea: '963', Pais: 'Síria', Sigla: 'SY' },
  { CodigoArea: '252', Pais: 'Somália', Sigla: 'SO' },
  { CodigoArea: '94', Pais: 'Sri Lanka', Sigla: 'LK' },
  { CodigoArea: '1869', Pais: 'St. Kitts e Névis', Sigla: 'KN' },
  { CodigoArea: '268', Pais: 'Suazilândia', Sigla: 'SZ' },
  { CodigoArea: '249', Pais: 'Sudão', Sigla: 'SD' },
  { CodigoArea: '46', Pais: 'Suécia', Sigla: 'SE' },
  { CodigoArea: '41', Pais: 'Suíça', Sigla: 'CH' },
  { CodigoArea: '597', Pais: 'Suriname', Sigla: 'SR' },
  { CodigoArea: '', Pais: 'Svalbard', Sigla: 'SJ' },
  { CodigoArea: '992', Pais: 'Tagiquistão', Sigla: 'TJ' },
  { CodigoArea: '66', Pais: 'Tailândia', Sigla: 'TH' },
  { CodigoArea: '886', Pais: 'Taiwan', Sigla: 'TW' },
  { CodigoArea: '255', Pais: 'Tanzânia', Sigla: 'TZ' },
  {
    CodigoArea: '',
    Pais: 'Terras Austrais e Antárticas Francesas',
    Sigla: 'TF',
  },
  {
    CodigoArea: '',
    Pais: 'Território Britânico do Oceano Índico',
    Sigla: 'IO',
  },
  { CodigoArea: '', Pais: 'Territórios Insulares dos EUA', Sigla: 'UM' },
  { CodigoArea: '670', Pais: 'Timor Leste', Sigla: 'TP' },
  { CodigoArea: '228', Pais: 'Togo', Sigla: 'TG' },
  { CodigoArea: '690', Pais: 'Tokelau', Sigla: 'TK' },
  { CodigoArea: '676', Pais: 'Tonga', Sigla: 'TO' },
  { CodigoArea: '1868', Pais: 'Trinidad e Tobago', Sigla: 'TT' },
  { CodigoArea: '216', Pais: 'Tunísia', Sigla: 'TN' },
  { CodigoArea: '993', Pais: 'Turcomenistão', Sigla: 'TM' },
  { CodigoArea: '90', Pais: 'Turquia', Sigla: 'TR' },
  { CodigoArea: '688', Pais: 'Tuvalu', Sigla: 'TV' },
  { CodigoArea: '380', Pais: 'Ucrânia', Sigla: 'UA' },
  { CodigoArea: '256', Pais: 'Uganda', Sigla: 'UG' },
  { CodigoArea: '598', Pais: 'Uruguai', Sigla: 'UY' },
  { CodigoArea: '998', Pais: 'Uzbequistão', Sigla: 'UZ' },
  { CodigoArea: '678', Pais: 'Vanuatu', Sigla: 'VU' },
  { CodigoArea: '58', Pais: 'Venezuela', Sigla: 'VE' },
  { CodigoArea: '84', Pais: 'Vietnã', Sigla: 'VN' },
  { CodigoArea: '681', Pais: 'Wallis e Futuna', Sigla: 'WF' },
  { CodigoArea: '260', Pais: 'Zâmbia', Sigla: 'ZM' },
  { CodigoArea: '263', Pais: 'Zimbábue', Sigla: 'ZW' },
];
